const fontFamilies =
  'Roboto Flex, -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Fira Sans, Droid Sans, Helvetica Neue, sans-serif';

export const typography = {
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  fontFamily: fontFamilies,
  fontSize: '18px',
  h1: {
    fontFamily: fontFamilies,
    fontWeight: 300,
    fontStretch: '110%',
    fontSize: '6rem',
    lineHeight: 1.3,
    letterSpacing: '-0.01562em',
  },
  h2: {
    fontFamily: fontFamilies,
    fontWeight: 300,
    fontStretch: '110%',
    fontSize: '3.75rem',
    lineHeight: 1.2,
    letterSpacing: '-0.00833em',
  },
  h3: {
    fontFamily: fontFamilies,
    fontWeight: 400,
    fontStretch: '110%',
    fontSize: '3rem',
    lineHeight: 1.167,
    letterSpacing: '0em',
  },
  h4: {
    fontFamily: fontFamilies,
    fontWeight: 400,
    fontStretch: '110%',
    fontSize: '2.125rem',
    lineHeight: 1.235,
    letterSpacing: '0.00735em',
  },
  h5: {
    fontFamily: fontFamilies,
    fontWeight: 400,
    fontStretch: '110%',
    letterSpacing: '0em',
    fontSize: '1.5rem',
    lineHeight: 1.334,
  },
  h6: {
    fontFamily: fontFamilies,
    fontWeight: 500,
    fontStretch: '110%',
    fontSize: '1.25rem',
    lineHeight: 1.6,
    letterSpacing: '0.0075em',
  },
  subtitle1: {
    fontFamily: fontFamilies,
    fontWeight: 800,
    fontStretch: '110%',
    fontSize: '0.975rem',
    lineHeight: 1.4,
    letterSpacing: '0.03em',
  },
  subtitle2: {
    fontFamily: fontFamilies,
    fontWeight: 500,
    fontStretch: '110%',
    fontSize: '0.875rem',
    lineHeight: 1.3,
    letterSpacing: '0.00714em',
  },
  body1: {
    fontFamily: fontFamilies,
    fontWeight: 400,
    fontStretch: '100%',
    fontSize: '1rem',
    lineHeight: 1.5,
    letterSpacing: '0.00938em',
  },
  body2: {
    fontFamily: fontFamilies,
    fontWeight: 400,
    fontStretch: '100%',
    fontSize: '0.875rem',
    lineHeight: 1.43,
    letterSpacing: '0.01071em',
  },
  button: {
    fontFamily: fontFamilies,
    fontWeight: 500,
    fontStretch: '110%',
    fontSize: '0.875rem',
    lineHeight: 1.75,
    letterSpacing: '0.02857em',
    textTransform: 'uppercase',
  },
  caption: {
    fontFamily: fontFamilies,
    fontWeight: 400,
    fontStretch: '110%',
    fontSize: '0.75rem',
    lineHeight: 1.66,
    letterSpacing: '0.03333em',
  },
};

export default typography;
